apiVersion: batch/v1
kind: Job
metadata:
  name: tumladan-migrate
  namespace: tumladan
  labels:
    app.kubernetes.io/name: tumladan-migrate
    app.kubernetes.io/part-of: tumladan
spec:
  backoffLimit: 4
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tumladan-migrate
        app.kubernetes.io/part-of: tumladan
    spec:
      restartPolicy: Never
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        runAsGroup: 10001
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: migrate
          image: ghcr.io/lemeshkinaveronika/2026_webmafia_tumladan:latest
          imagePullPolicy: IfNotPresent
          command: ["/migrate"]
          args: ["-path=/migrations", "-database=$(DATABASE_URL)", "up"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: tumladan-secrets
                  key: DATABASE_URL
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 200m
              memory: 128Mi

