apiVersion: v1
kind: Service
metadata:
  name: tumladan-api
  namespace: tumladan
  labels:
    app.kubernetes.io/name: tumladan-api
    app.kubernetes.io/part-of: tumladan
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: tumladan-api
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP

